name: Run tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'assets/coverage.svg'
    pull_requests:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install .
          pip install pytest pytest-cov

      - name: Run tests
        run: pytest

      - name: Update coverage
        run: |
          coverage-badge -o assets/coverage.svg
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/coverage.svg
          git commit -m "Updated coverage badge" || echo "No changes"
          git push

